# Generated by Django 5.0 on 2024-10-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('anime_type', models.CharField(max_length=50)),
                ('year', models.IntegerField(null=True)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('large_image_url', models.URLField()),
                ('episodes', models.IntegerField(null=True)),
                ('favorites', models.IntegerField(default=0)),
                ('members', models.IntegerField(default=0)),
                ('popularity', models.IntegerField(null=True)),
                ('rank', models.IntegerField(null=True)),
                ('score', models.FloatField(null=True)),
                ('scored_by', models.IntegerField(default=0)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('genres', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mal_id'], name='game_anime_mal_id_5d8703_idx'), models.Index(fields=['title'], name='game_anime_title_33953b_idx')],
            },
        ),
    ]
